# TODO: Let's see if this experiment helps DRYs settings and arguments
# TODO: This file itself could use a bit of DRYing. I.e. The experiment is not working.

# This contains, so far, Config objects that are just arguments to various actions
# that digi_leap.py can perform.
# The key for the Config object is the command line argument name.
#  Config objects contain these fields:
#   - The default value (optional) for the command line argument.
#   - The help text (optional) for the command line argument.
#   - The type (optional) arg types can be determined from the default value but if
#     there is no default value then you can use this field.
#   - The choices field is for a controlled vocabulary argument
#   - Required
# There are a lot of common values for arguments at the top and the per module arguments
# are grouped by module name below them.

# Root dir for the label babel data
label_babel_dir: &label_babel_dir !Config
    type: !Path .
    help: Base directory for Label Babel data.

# The most recent models
curr_model_name: &curr_model_name !Config
    default:  faster_rcnn_2021-08-18
    help: The name of the model being used to find labels on herbarium sheets.

prev_model_name: &prev_model_name !Config
    type: !Path .
    help: The name of the model previous used to find labels on herbarium sheets.

image_filter: &image_filter !Config
  default: "*.jpg"
  help: Glob images in the given directory with this pattern.

# GPU jobs
device: &device !Config
  default: cuda:0
  help: Which GPU or CPU to use. Options are 'cpu', 'cuda:0', 'cuda:1', etc.

gpu_batch: &gpu_batch !Config
  default: 2
  help: Input batch size for model batches.

workers: &workers !Config
  default: 2
  help: Number of workers for loading data.

# Processes and threads
proc_cpus: &proc_cpus !Config
  default:  6
  help: How many process to spawn for running this job.

proc_batch: &proc_batch !Config
  default: 10
  help: How many items to put in each spawned CPU batch.

threads: &threads !Config
  default: 20
  help:

row_batch: &row_batch !Config
  default: 1_000_000
  help: Batch size when loading large data sets.

nms_threshold: &nms_threshold !Config
  default: 0.3
  help: IoU overlap to use for non-maximum suppression.

sbs_threshold: &sbs_threshold !Config
  default: 0.95
  help: IoU overlap to use for small box suppression

limit: &limit !Config
  type: 1
  help: Limit the input to this many records.

label_babel: &label_babel !Config
    default: 17633_label_babel_2
    help: Name of a Label Babel expedition.

sheets_dir: &sheets_dir !Config
  default: !Path "{label_babel_dir}/herbarium-sheets-small"
  help: The directory containing the herbarium sheet images.

unreconciled_csv: &unreconciled_csv !Config
  default: !Path "{label_babel_dir}/17633_label_babel_2.unreconciled.csv"
  help: Unreconciled CSV data from a Label Babel expedtion.

reconciled_jsonl: &reconciled_jsonl !Config
  default: !Path "{label_babel_dir}/{label_babel}.reconciled.jsonl"
  help: Reconciled JSONL data from a Label Babel expedtion.

prep_dir: &prep_dir !Config
  default: !Path output/prepared_{curr_model_name}_deskew
  help: The directory that holds prepared label images.

ensemble_image_dir: &ensemble_image_dir !Config
  type: !Path .
  help: OCR ensemble images are in this directory.

ensemble_text_dir: &ensemble_text_dir !Config
  type: !Path .
  help: OCR ensemble text is in directory.

idigbio_db: &idigbio_db !Config
  default: !Path data/processed/occurrence_raw_2021-02.sqlite3.db
  help: Database that holds processed iDigBio data.

idigbio_zip_file: &idigbio_zip_file !Config
  default: !Path data/raw/iDigBio_snapshot_2021-02.zip
  help: Zip file that holds raw iDigBio data.

itis_db: &itis_db !Config
  default: !Path data/ITIS.sqlite
  help: ITIS database.

label_dir: &label_dir !Config
  default: !Path "{label_babel_dir}/{curr_model_name}"
  help: Directory containing cropped labels from herbarium sheets.

curr_model: &curr_model !Config
  default: !Path models/{curr_model_name}.pth
  help: Path to the current model for finding labels on a herbarium sheet.

pipeline: &pipeline !Config
  default: deskew
  help: A pipeline of image transformations that may help with the OCR process.

ocr_engine: &ocr_engine !Config
  default: tesseract
  choices: [tesseract, easyocr]
  help: Which OCR engine to use.


# ############################################################################
# Default arguments for scripts

faster_rcnn_test:
  help: |-
    Test a model that finds labels on herbarium sheets (inference with scoring).
  reconciled_jsonl: *reconciled_jsonl
  sheets_dir:       *sheets_dir
  load_model:       *curr_model
  nms_threshold:    *nms_threshold
  sbs_threshold:    *sbs_threshold
  device:           *device
  batch_size:       *gpu_batch
  workers:          *workers
  limit:            *limit


faster_rcnn_train:
  help: |-
    Train a model to find labels on herbarium sheets.
  reconciled_jsonl: *reconciled_jsonl
  sheets_dir:       *sheets_dir
  save_model:       *curr_model
  load_model: !Config
    default: ""
    help: Load this model to continue training.
  batch_size:       *gpu_batch
  device:           *device
  nms_threshold:    *nms_threshold
  sbs_threshold:    *sbs_threshold
  workers:          *workers
  limit:            *limit
  epochs: !Config
    default: 100
    help: How many epochs for training the model.
  learning_rate: !Config
    default: 0.005
    help: The learning rate for training the model.
  split: !Config
    default: 0.25
    help: The train/validataion split for training the model.


faster_rcnn_use:
  help: |-
    Use a model that finds labels on herbarium sheets (inference).
  sheets_dir:    *sheets_dir
  label_dir:     *label_dir
  glob:          *image_filter
  load_model:    *curr_model
  device:        *device
  nms_threshold: *nms_threshold
  sbs_threshold: *sbs_threshold
  limit:         *limit


idigbio_images:
  help: |-
    Use iDigBio records to download images. You should extract an iDigBio media
    file from a snapshot before running this.
  sheets_dir: *sheets_dir
  csv_file: !Config
    default: data/sernec/sernec_multimedia.csv
    help: The CSV file that contiains the image URL.
  sample_size: !Config
    default: 10_000
    help: How many records to sample from the CSV file.
  url_column: !Config
    default: accessURI
    help: Which column contains the image URI.


idigbio_load:
  zip_file: *idigbio_zip_file
  database: *idigbio_db
  batch:    *row_batch
  csv_file: !Config
    default: occurrence_raw.csv
    help: The raw CSV file inside of the zip file.
  table_name: !Config
    default: occurrence_raw
    help: What to call the table containing the processed data.
  col_filters: !Config
    default:
      - .
    help: Which columns to extract from the raw CSV file.
  row_filters: !Config
    default:
      - plant@dwc:kingdom
      - .@dwc:scientificName
    help: Filter rows in the raw CSV file.


itis_taxa:
  lang: !Config
    default: en_US
    help:


label_babel_reconcile:
  nothing: !Config
    help:


ocr_ensemble:
  help: |-
    Build a single "best" label from the ensemble of OCR outputs.
    An ensemble is a list of OCR outputs with the same name contained
    in parallel directories. For instance, if you have OCR output
    (from the ocr_labels action) for three different runs then an ensemble
    will be:
        output/ocr/run1/label1.csv
        output/ocr/run2/label1.csv
        output/ocr/run3/label1.csv
  ocr_dir: !Config
    default: output/ocr_*
    help: The set of OCR output directories to use for the ensemble.
  ensemble_images: *ensemble_image_dir
  ensemble_text:   *ensemble_text_dir
  prepared_dir:    *prep_dir
  winners_jsonl: !Config
    type: !Path .
    help: Save data on which OCR results were used in the output.
  cpus:            *proc_cpus
  batch_size:      *proc_batch
  limit:           *limit
  line_space: !Config
    default: 8
    help: Margin between lines of text in the reconstructed label output.
  label_filter: !Config
    type: ""
    help: Filter files for debugging specific labels.


ocr_expedition:
  ensemble_images: *ensemble_image_dir
  ensemble_text:   *ensemble_text_dir
  label_dir:       *label_dir
  expedition_dir: !Config
    type: !Path .
    help: Where the expedition files are.
  filter_rulers: !Config
    default: 2.0
    help: |-
      Consider a label to be a ruler if the height:width (or width:height)
      ratio is above this.
  largest_labels: !Config
    default: 1
    help: Keep the N largest labels.
  word_count_threshold: !Config
    default: 20
    help: Skip labels with fewer than this many words.
  vocab_count_threshold: !Config
    default: 10
    help: Skip labels with fewer than this vocabulary hits.
  filter_types: !Config
    default:
      - Barcode
      - Both
      - Handwritten
    help: Remove labels if they fall into any of these categories.


ocr_in_house_qc:
  help: |-
    Build a single "best" label from the ensemble of OCR outputs.
  qc_dir: !Config
    default: !Path data/temp/qc_{curr_model_name}
    help:
  ensemble_images:  *ensemble_image_dir
  ensemble_text:    *ensemble_text_dir
  reconciled_jsonl: *reconciled_jsonl
  sheets_dir:       *sheets_dir
  sample_size: !Config
    default: 25
    help:


ocr_labels:
  help: |-
    OCR images of labels.
  prepared_dir: *prep_dir
  output_dir: !Config
    type: !Path .
    help: Put OCR output for labels into this directory.
  ocr_engine: *ocr_engine
  glob:       *image_filter
  cpus:       *proc_cpus
  batch_size: *proc_batch
  limit:      *limit


ocr_prepare:
  help: |-
    Prepare images of labels for OCR. Perform image manipuations on labels that
    may help with the OCR process.
  label_dir:  *label_dir
  output_dir: *prep_dir
  pipeline:   *pipeline
  cpus:       *proc_cpus
  batch_size: *proc_batch
  glob:       *image_filter
  limit:      *limit
